
server.port=8087

spring.application.name=auth-service

# =========================================================
# MYSQL
# =========================================================

spring.datasource.url=jdbc:mysql://localhost:3306/auth_db

spring.datasource.username=root

spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================================================
# JPA
# =========================================================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# =========================================================
# EUREKA
# =========================================================

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# =========================================================
# JWT
# =========================================================

jwt.secret=${JWT_SECRET:MyVeryLongSuperSecretJwtKeyForLibraryManagementSystem2026SecureTokenGeneration}
jwt.expiration=${JWT_EXPIRATION:86400000}
internal.api.key=${INTERNAL_API_KEY:BiblioInternalCommunicationKey2026Secure}

# =========================================================
# SWAGGER
# =========================================================

springdoc.api-docs.enabled=true

springdoc.swagger-ui.enabled=true

springdoc.swagger-ui.path=/swagger-ui.html

# =========================================================
# LOGGING
# =========================================================
logging.level.com.library.auth_service=DEBUG

# Administrador inicial.
# Debe habilitarse solo una vez mediante variables de entorno.
app.bootstrap.admin.enabled=${BOOTSTRAP_ADMIN_ENABLED:false}
app.bootstrap.admin.name=${BOOTSTRAP_ADMIN_NAME:}
app.bootstrap.admin.email=${BOOTSTRAP_ADMIN_EMAIL:}
app.bootstrap.admin.password=${BOOTSTRAP_ADMIN_PASSWORD:}
